name: snap_env
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - asgiref=3.5.2
  - blas=1.0
  - bottleneck=1.3.7
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - cffi=1.16.0
  - cryptography=41.0.7
  - django=4.1
  - django-filter=23.5
  - djangorestframework=3.15.1
  - dnspython=2.4.2
  - expat=2.5.0
  - greenlet=3.0.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - krb5=1.20.1
  - libexpat=2.5.0
  - libffi=3.4.4
  - libiconv=1.16
  - libpq=12.17
  - libsqlite=3.45.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.3
  - markdown=3.4.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.2.1
  - pandas=2.2.1
  - pip=23.3.1
  - psycopg2=2.9.9
  - pycparser=2.21
  - pymongo=4.6.3
  - pymysql=1.0.2
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - setuptools=68.2.2
  - six=1.16.0
  - sqlalchemy=2.0.25
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.13
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - ucrt=10.0.20348.0
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - django-rest-framework-mongoengine==3.4.1
      - mongoengine==0.28.2
      - pillow==10.3.0
      - sqlparse==0.2.4
